const { PDFDocument, rgb, StandardFonts } = require('pdf-lib');

const generateBookPDF = async (book, chapters, options = {}) => {
  const pdfDoc = await PDFDocument.create();

  const titleFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const bodyFont = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const italicFont = await pdfDoc.embedFont(StandardFonts.HelveticaOblique);

  const pageWidth = 595.28; // A4
  const pageHeight = 841.89;
  const margin = 72;
  const contentWidth = pageWidth - 2 * margin;

  const selectedTheme = options.themeColor || book.themeColor || 'purple';

  const COLOR_PALETTES = {
    purple: {
      title: rgb(0.24, 0.14, 0.65),
      subtitle: rgb(0.4, 0.4, 0.6),
      body: rgb(0.1, 0.1, 0.1),
      accent: rgb(0.48, 0.23, 0.93),
      light: rgb(0.6, 0.6, 0.6),
      white: rgb(1, 1, 1),
      bg: rgb(0.97, 0.97, 1.0)
    },
    blue: {
      title: rgb(0.11, 0.31, 0.65),
      subtitle: rgb(0.3, 0.45, 0.65),
      body: rgb(0.1, 0.15, 0.2),
      accent: rgb(0.14, 0.54, 0.88),
      light: rgb(0.5, 0.6, 0.7),
      white: rgb(1, 1, 1),
      bg: rgb(0.95, 0.98, 1.0)
    },
    emerald: {
      title: rgb(0.04, 0.4, 0.28),
      subtitle: rgb(0.3, 0.5, 0.4),
      body: rgb(0.1, 0.2, 0.15),
      accent: rgb(0.06, 0.62, 0.43),
      light: rgb(0.5, 0.65, 0.55),
      white: rgb(1, 1, 1),
      bg: rgb(0.95, 0.99, 0.96)
    },
    amber: {
      title: rgb(0.6, 0.35, 0.05),
      subtitle: rgb(0.6, 0.45, 0.2),
      body: rgb(0.2, 0.15, 0.1),
      accent: rgb(0.85, 0.5, 0.08),
      light: rgb(0.65, 0.55, 0.45),
      white: rgb(1, 1, 1),
      bg: rgb(0.99, 0.98, 0.94)
    },
    crimson: {
      title: rgb(0.6, 0.08, 0.15),
      subtitle: rgb(0.6, 0.3, 0.35),
      body: rgb(0.2, 0.1, 0.1),
      accent: rgb(0.88, 0.15, 0.25),
      light: rgb(0.65, 0.5, 0.5),
      white: rgb(1, 1, 1),
      bg: rgb(0.99, 0.95, 0.95)
    },
    dark: {
      title: rgb(0.1, 0.12, 0.18),
      subtitle: rgb(0.4, 0.45, 0.55),
      body: rgb(0.15, 0.18, 0.24),
      accent: rgb(0.25, 0.3, 0.42),
      light: rgb(0.5, 0.55, 0.65),
      white: rgb(1, 1, 1),
      bg: rgb(0.94, 0.95, 0.97)
    }
  };

  const colors = COLOR_PALETTES[selectedTheme] || COLOR_PALETTES.purple;

  // ---- COVER PAGE ----
  const coverPage = pdfDoc.addPage([pageWidth, pageHeight]);

  // Background gradient simulation
  coverPage.drawRectangle({ x: 0, y: 0, width: pageWidth, height: pageHeight, color: colors.bg });
  coverPage.drawRectangle({ x: 0, y: pageHeight * 0.55, width: pageWidth, height: pageHeight * 0.45, color: colors.title });

  // Book title
  const titleSize = Math.min(36, Math.max(20, 400 / (book.title.length || 1)));
  const titleLines = wrapText(book.title, titleFont, titleSize, contentWidth);
  let titleY = pageHeight * 0.82;
  for (const line of titleLines) {
    const w = titleFont.widthOfTextAtSize(line, titleSize);
    coverPage.drawText(line, {
      x: (pageWidth - w) / 2, y: titleY,
      size: titleSize, font: titleFont, color: colors.white
    });
    titleY -= titleSize * 1.4;
  }

  // Subtitle
  if (book.subtitle) {
    const subLines = wrapText(book.subtitle, italicFont, 16, contentWidth);
    let subY = titleY - 10;
    for (const line of subLines) {
      const w = italicFont.widthOfTextAtSize(line, 16);
      coverPage.drawText(line, {
        x: (pageWidth - w) / 2, y: subY,
        size: 16, font: italicFont, color: rgb(0.85, 0.85, 1)
      });
      subY -= 22;
    }
  }

  // Author
  if (book.author) {
    const authorText = `by ${book.author}`;
    const aw = italicFont.widthOfTextAtSize(authorText, 18);
    coverPage.drawText(authorText, {
      x: (pageWidth - aw) / 2, y: pageHeight * 0.58,
      size: 18, font: italicFont, color: colors.white
    });
  }

  // Genre & info box
  const infoY = pageHeight * 0.3;
  coverPage.drawRectangle({ x: margin, y: infoY - 20, width: contentWidth, height: 100, color: rgb(1, 1, 1), borderColor: colors.accent, borderWidth: 1 });
  const infoItems = [
    `Genre: ${book.genre || 'General'}`,
    `Language: ${book.language || 'English'}`,
    `Tone: ${book.tone || 'Professional'}`,
    `Chapters: ${chapters.length}`
  ];
  let infoTextY = infoY + 60;
  for (const item of infoItems) {
    coverPage.drawText(item, { x: margin + 16, y: infoTextY, size: 11, font: bodyFont, color: colors.subtitle });
    infoTextY -= 18;
  }

  // Footer
  const genDate = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const footerText = `Generated by AI-Powered eBook Creator • ${genDate}`;
  const fw = bodyFont.widthOfTextAtSize(footerText, 9);
  coverPage.drawText(footerText, { x: (pageWidth - fw) / 2, y: 30, size: 9, font: bodyFont, color: colors.light });

  // ---- TABLE OF CONTENTS ----
  if (chapters.length > 0) {
    const tocPage = pdfDoc.addPage([pageWidth, pageHeight]);
    tocPage.drawRectangle({ x: 0, y: 0, width: pageWidth, height: pageHeight, color: colors.bg });
    tocPage.drawText('Table of Contents', {
      x: margin, y: pageHeight - margin,
      size: 28, font: titleFont, color: colors.title
    });
    tocPage.drawLine({ start: { x: margin, y: pageHeight - margin - 10 }, end: { x: pageWidth - margin, y: pageHeight - margin - 10 }, thickness: 2, color: colors.accent });

    let tocY = pageHeight - margin - 40;
    chapters.forEach((ch, idx) => {
      if (tocY < margin + 30) return;
      tocPage.drawText(`${idx + 1}.  ${ch.title}`, {
        x: margin, y: tocY, size: 13, font: bodyFont, color: colors.body
      });
      const wordCountText = `${ch.wordCount || 0} words`;
      const wcw = bodyFont.widthOfTextAtSize(wordCountText, 10);
      tocPage.drawText(wordCountText, {
        x: pageWidth - margin - wcw, y: tocY,
        size: 10, font: italicFont, color: colors.light
      });
      tocY -= 28;
    });
  }

  // ---- CHAPTER PAGES ----
  for (let i = 0; i < chapters.length; i++) {
    const chapter = chapters[i];
    const chapterPage = pdfDoc.addPage([pageWidth, pageHeight]);
    chapterPage.drawRectangle({ x: 0, y: 0, width: pageWidth, height: pageHeight, color: colors.bg });

    // Chapter header bar
    chapterPage.drawRectangle({ x: 0, y: pageHeight - 100, width: pageWidth, height: 100, color: colors.title });
    chapterPage.drawText(`Chapter ${i + 1}`, {
      x: margin, y: pageHeight - 50,
      size: 13, font: bodyFont, color: rgb(0.7, 0.7, 1)
    });
    const chTitleLines = wrapText(chapter.title, titleFont, 22, contentWidth);
    let chTitleY = pageHeight - 72;
    for (const line of chTitleLines) {
      chapterPage.drawText(line, { x: margin, y: chTitleY, size: 22, font: titleFont, color: colors.white });
      chTitleY -= 28;
    }

    // Chapter content
    const rawContent = stripHtml(chapter.content || '');
    const paragraphs = rawContent.split('\n').filter(p => p.trim().length > 0);

    let currentPage = chapterPage;
    let y = pageHeight - 130;

    for (const paragraph of paragraphs) {
      const lines = wrapText(paragraph.trim(), bodyFont, 11, contentWidth);
      for (const line of lines) {
        if (y < margin + 30) {
          currentPage = pdfDoc.addPage([pageWidth, pageHeight]);
          currentPage.drawRectangle({ x: 0, y: 0, width: pageWidth, height: pageHeight, color: colors.bg });
          y = pageHeight - margin;
        }
        currentPage.drawText(line, {
          x: margin, y,
          size: 11, font: bodyFont, color: colors.body
        });
        y -= 16;
      }
      y -= 10; // paragraph spacing
    }

    // Page number
    const pageNum = `— ${i + 2} —`;
    const pnw = bodyFont.widthOfTextAtSize(pageNum, 10);
    currentPage.drawText(pageNum, { x: (pageWidth - pnw) / 2, y: 25, size: 10, font: bodyFont, color: colors.light });
  }

  return await pdfDoc.save();
};

const wrapText = (text, font, size, maxWidth) => {
  const words = (text || '').split(' ');
  const lines = [];
  let currentLine = '';

  for (const word of words) {
    const testLine = currentLine ? `${currentLine} ${word}` : word;
    try {
      const width = font.widthOfTextAtSize(testLine, size);
      if (width > maxWidth && currentLine) {
        lines.push(currentLine);
        currentLine = word;
      } else {
        currentLine = testLine;
      }
    } catch {
      currentLine = testLine;
    }
  }
  if (currentLine) lines.push(currentLine);
  return lines;
};

const stripHtml = (html) => {
  return html
    .replace(/<br\s*\/?>/gi, '\n')
    .replace(/<\/p>/gi, '\n\n')
    .replace(/<\/h[1-6]>/gi, '\n')
    .replace(/<[^>]*>/g, '')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
};

module.exports = { generateBookPDF };
